# Generated by Django 5.0.4 on 2024-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker_personal_information',
            name='addr',
            field=models.TextField(default='India'),
        ),
        migrations.AddField(
            model_name='seeker_personal_information',
            name='curr_addr',
            field=models.TextField(default='India'),
        ),
        migrations.AlterField(
            model_name='seeker_education',
            name='clg_specialization',
            field=models.TextField(choices=[('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Web Development', 'Web Development'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Biology', 'Biology'), ('Mathematics', 'Mathematics'), ('Electrical Engineering', 'Electrical Engineering'), ('Other', 'Other')], default=None),
        ),
        migrations.AlterField(
            model_name='seeker_education',
            name='st_12_specialization',
            field=models.TextField(choices=[('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default=None),
        ),
    ]
