# Generated by Django 5.0.4 on 2024-04-10 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seeker_personal_information_addr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comapny_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_logo', models.ImageField(upload_to='company_logo/')),
                ('cname', models.TextField()),
                ('company_contact', models.TextField()),
                ('company_category', models.TextField(choices=[('Education', 'Education'), ('Pharmaceutical', 'Pharmaceutical'), ('Information Technology (IT)', 'Information Technology (IT)'), ('Finance and Banking', 'Finance and Banking'), ('Consulting and Professional Services', 'Consulting and Professional Services'), ('Other', 'Other')])),
                ('c_desc', models.TextField()),
                ('c_link', models.URLField()),
                ('c_addr', models.TextField()),
                ('country_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
